// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWCd6Nc-Mxt-QIKUrpIs8F2Zs33BIp2v8',
    appId: '1:1081483504024:web:1a39bdadcc6493c6c763ed',
    messagingSenderId: '1081483504024',
    projectId: 'hr-startup-92d19',
    authDomain: 'hr-startup-92d19.firebaseapp.com',
    storageBucket: 'hr-startup-92d19.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApS19Jgzfxt70RdauoihqoPBxVs1W49Kc',
    appId: '1:1081483504024:android:3f8a9ef453573c3bc763ed',
    messagingSenderId: '1081483504024',
    projectId: 'hr-startup-92d19',
    storageBucket: 'hr-startup-92d19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3I72iFzC5uXYOj8PqjgJCj4iXF2U2EFA',
    appId: '1:1081483504024:ios:9ec6b34d7053f82ec763ed',
    messagingSenderId: '1081483504024',
    projectId: 'hr-startup-92d19',
    storageBucket: 'hr-startup-92d19.appspot.com',
    iosClientId:
        '1081483504024-cff3mvs2g61lbcul4q1jicb4gpn0kt7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3I72iFzC5uXYOj8PqjgJCj4iXF2U2EFA',
    appId: '1:1081483504024:ios:88480339f578f020c763ed',
    messagingSenderId: '1081483504024',
    projectId: 'hr-startup-92d19',
    storageBucket: 'hr-startup-92d19.appspot.com',
    iosClientId:
        '1081483504024-9npbdrdsetg851cckt8qquqbmiq56qa6.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrProject.RunnerTests',
  );
}
